{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  "enable_cpu_affinity": true,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "bf16",
  "num_machines": 1,
  "num_processes": 8,
  "rdzv_backend": "static",
  "same_network": true,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false,
  "fsdp_config":
    {
      "fsdp_auto_wrap_policy": "TRANSFORMER_BASED_WRAP",
      "fsdp_backward_prefetch_policy": "BACKWARD_PRE",
      "fsdp_forward_prefetch": true,
      "fsdp_offload_params": false,
      "fsdp_sharding_strategy": 1,
      "fsdp_state_dict_type": "FULL_STATE_DICT",
      "fsdp_transformer_layer_cls_to_wrap": ["Lfm2DecoderLayer"], # SmolLM3DecoderLayer, LlamaDecoderLayer,Qwen3DecoderLayer
    },
}
