# CHANGE THIS TO YOUR OWN DATASET
TTS_dataset: "kadirnar/qwen3-tokenized-Alhaitham"

model_name: "Vyvo/VyvoTTS-Qwen3-0.6B-PT"

# Training Args
epochs: 1
batch_size: 16
number_processes: 1
pad_token: 64407
save_steps: 5000
learning_rate: 5.0e-5

# Naming and paths
save_folder: "checkpoints"
project_name: "tuning-orpheus"
run_name: "5e5-0"
